-- Outbound merchant webhooks.
--
-- Operators register HTTP endpoints to receive order-state-change
-- events. Each delivery is signed via b.webhook — the consumer sees a
-- `Webhook-Signature` header (HMAC-SHA3-512 keyed by the per-endpoint
-- secret) and verifies with the framework's standard verifier.
--
-- Each endpoint owns:
--   url      — operator-supplied https:// destination (http:// is refused)
--   secret   — generated by the framework, returned ONCE on create.
--              The operator records it for verification; the framework
--              never reveals it again (the row stays for outbound use).
--   events   — comma-separated event type allowlist OR `*` for all.
--              Known types: order.mark_paid, order.start_fulfillment,
--              order.mark_shipped, order.mark_delivered, order.cancel,
--              order.refund. Adding a new transition surfaces the new
--              event type to every `*` endpoint automatically.
--   active   — 0 disables delivery without dropping the row (operators
--              pause an endpoint during incident response without
--              losing the configured destination + secret).
--
-- Deliveries are persisted before the outbound HTTP call so a crash
-- mid-delivery leaves an `attempts=0` audit row behind. On HTTP 1xx-
-- 3xx the row flips to `delivered_at = <ts>` + `last_status = <code>`.
-- On 4xx/5xx (or transport error) the row holds `last_error = <msg>`
-- so the admin UI can retry the delivery later.

CREATE TABLE IF NOT EXISTS webhook_endpoints (
  id           TEXT NOT NULL PRIMARY KEY,
  url          TEXT NOT NULL,
  secret       TEXT NOT NULL,
  events       TEXT NOT NULL,
  active       INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  created_at   INTEGER NOT NULL,
  updated_at   INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_webhook_endpoints_active ON webhook_endpoints(active);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
  id             TEXT NOT NULL PRIMARY KEY,
  endpoint_id    TEXT NOT NULL,
  event_type     TEXT NOT NULL,
  payload_json   TEXT NOT NULL,
  attempts       INTEGER NOT NULL DEFAULT 0,
  last_status    INTEGER,
  last_error     TEXT,
  delivered_at   INTEGER,
  created_at     INTEGER NOT NULL,
  FOREIGN KEY (endpoint_id) REFERENCES webhook_endpoints(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_endpoint ON webhook_deliveries(endpoint_id, created_at);
