"use strict";
/**
 * @module shop.webhooks
 * @title  Outbound merchant webhooks — operator-registered receivers
 *
 * @intro
 *   Operators register HTTP endpoints to receive order-state-change
 *   events. Each delivery is signed via the upstream `b.webhook`
 *   signer — the receiver verifies the framework's standard
 *   `Webhook-Signature` header (HMAC-SHA3-512 with the per-endpoint
 *   secret) using `b.webhook.verifier({...}).verify(...)`.
 *
 *   The per-endpoint secret is generated by the framework via
 *   `b.crypto.generateToken(32)` and returned ONCE on create. The
 *   operator records it for verification; the framework never reveals
 *   it again (rows stay for outbound use only).
 *
 *   `events` is either the wildcard `*` or a comma-separated allowlist
 *   of recognized event types — `order.mark_paid`,
 *   `order.start_fulfillment`, `order.mark_shipped`,
 *   `order.mark_delivered`, `order.cancel`, `order.refund`. Endpoints
 *   only receive event types they subscribed to.
 *
 *   `send(eventType, payload)` is fire-and-flag-failure: every active
 *   endpoint subscribed to the event gets a delivery row before the
 *   outbound POST runs. On HTTP 1xx-3xx the row flips to
 *   `delivered_at = <ts>` + `last_status = <code>`; on 4xx/5xx (or
 *   transport error) the row holds `last_error` and a single retry
 *   runs via `b.retry.withRetry`. The framework returns the array of
 *   delivery rows so the caller (typically the order primitive) can
 *   surface failures to the operator's audit pipeline.
 *
 *   The idempotency key bound into the signed string is a fresh
 *   `b.uuid.v7()` per delivery — re-deliveries (manual retry) carry a
 *   new id so the consumer's nonce store doesn't reject the replay as
 *   a duplicate.
 */

var bShop;
function _b() {
  if (!bShop) bShop = require("./index");
  return bShop.framework;
}

var KNOWN_EVENTS = Object.freeze([
  "order.mark_paid",
  "order.start_fulfillment",
  "order.mark_shipped",
  "order.mark_delivered",
  "order.cancel",
  "order.refund",
]);

var SECRET_BYTES = 32;

function _now() { return Date.now(); }

function _validateUrl(url) {
  if (typeof url !== "string" || url.length === 0) {
    throw new TypeError("webhooks: url must be a non-empty string");
  }
  // Refuse http:// outright for outbound — the framework's safe-url
  // parser carries the ALLOW_HTTP_TLS preset that admits only https.
  try {
    _b().safeUrl.parse(url, { allowedProtocols: ["https:"] });
  } catch (e) {
    throw new TypeError("webhooks: url must be https:// — " + (e && e.message || "rejected"));
  }
}

function _validateEvents(events) {
  if (typeof events !== "string" || events.length === 0) {
    throw new TypeError("webhooks: events must be a non-empty string ('*' or comma-separated event types)");
  }
  if (events === "*") return "*";
  var parts = events.split(",").map(function (s) { return s.trim(); }).filter(Boolean);
  if (parts.length === 0) {
    throw new TypeError("webhooks: events must list at least one event type");
  }
  for (var i = 0; i < parts.length; i += 1) {
    if (KNOWN_EVENTS.indexOf(parts[i]) === -1) {
      throw new TypeError("webhooks: unknown event type " + JSON.stringify(parts[i]) +
        " — known: " + KNOWN_EVENTS.join(", "));
    }
  }
  return parts.join(",");
}

function _matchEvents(subscribedCsv, eventType) {
  if (subscribedCsv === "*") return true;
  var parts = subscribedCsv.split(",");
  for (var i = 0; i < parts.length; i += 1) {
    if (parts[i] === eventType) return true;
  }
  return false;
}

function _uuid(s, label) {
  try { return _b().guardUuid.sanitize(s, { profile: "strict" }); }
  catch (e) { throw new TypeError("webhooks: " + label + " — " + (e && e.message || "invalid UUID")); }
}

// _defaultTransport — composes b.httpClient.request for production.
// Test wiring injects a stub via deps.transport so the delivery path
// is exercised without an actual outbound POST.
function _defaultTransport(req) {
  return _b().httpClient.request({
    method:  "POST",
    url:     req.url,
    headers: req.headers,
    body:    req.body,
  });
}

function create(opts) {
  opts = opts || {};
  var query = opts.query;
  if (!query) {
    query = function (sql, params) { return _b().externalDb.query(sql, params); };
  }
  var transport = typeof opts.transport === "function" ? opts.transport : _defaultTransport;
  var retryOpts = opts.retry || { maxAttempts: 2, baseDelayMs: 25, maxDelayMs: 250 };

  async function _deliver(endpointRow, eventType, payloadJson) {
    var deliveryId = _b().uuid.v7();
    var createdAt  = _now();
    await query(
      "INSERT INTO webhook_deliveries (id, endpoint_id, event_type, payload_json, attempts, created_at) " +
      "VALUES (?1, ?2, ?3, ?4, 0, ?5)",
      [deliveryId, endpointRow.id, eventType, payloadJson, createdAt],
    );
    return await _attempt(deliveryId, endpointRow, eventType, payloadJson);
  }

  async function _attempt(deliveryId, endpointRow, eventType, payloadJson) {
    var signer = _b().webhook.signer({
      algo:        "hmac-sha3-512",
      keys:        { v1: Buffer.from(endpointRow.secret, "utf8") },
      defaultKid:  "v1",
      idGenerator: function () { return _b().uuid.v7().replace(/-/g, ""); },
    });
    var signed = signer.sign(payloadJson);
    var headers = Object.assign({
      "Content-Type":      "application/json",
      "Webhook-Event":     eventType,
      "Webhook-Delivery":  deliveryId,
    }, signed.headers);

    var status = 0;
    var errMsg = null;
    try {
      var res = await _b().retry.withRetry(function () {
        return transport({ url: endpointRow.url, headers: headers, body: payloadJson });
      }, retryOpts);
      status = (res && (res.statusCode || res.status)) || 0;
    } catch (e) {
      errMsg = (e && e.message) || String(e);
    }

    var ts = _now();
    var delivered = (status >= 100 && status < 400);
    if (delivered) {
      await query(
        "UPDATE webhook_deliveries SET attempts = attempts + 1, last_status = ?1, last_error = NULL, delivered_at = ?2 " +
        "WHERE id = ?3",
        [status, ts, deliveryId],
      );
    } else {
      await query(
        "UPDATE webhook_deliveries SET attempts = attempts + 1, last_status = ?1, last_error = ?2 " +
        "WHERE id = ?3",
        [status || null, errMsg || ("http-" + status), deliveryId],
      );
    }
    return await _getDelivery(deliveryId);
  }

  async function _getDelivery(id) {
    var r = await query("SELECT * FROM webhook_deliveries WHERE id = ?1", [id]);
    return r.rows[0] || null;
  }

  async function _getEndpoint(id) {
    var r = await query("SELECT * FROM webhook_endpoints WHERE id = ?1", [id]);
    return r.rows[0] || null;
  }

  return {
    KNOWN_EVENTS: KNOWN_EVENTS,

    endpoints: {
      create: async function (input) {
        if (!input || typeof input !== "object") throw new TypeError("webhooks.endpoints.create: input object required");
        _validateUrl(input.url);
        var events = _validateEvents(input.events);
        var id     = _b().uuid.v7();
        var secret = _b().crypto.generateToken(SECRET_BYTES);
        var ts     = _now();
        await query(
          "INSERT INTO webhook_endpoints (id, url, secret, events, active, created_at, updated_at) " +
          "VALUES (?1, ?2, ?3, ?4, 1, ?5, ?5)",
          [id, input.url, secret, events, ts],
        );
        return await _getEndpoint(id);
      },

      get: async function (id) {
        _uuid(id, "endpoint id");
        return await _getEndpoint(id);
      },

      list: async function () {
        var r = await query("SELECT * FROM webhook_endpoints ORDER BY created_at DESC", []);
        return r.rows;
      },

      update: async function (id, patch) {
        _uuid(id, "endpoint id");
        if (!patch || typeof patch !== "object") throw new TypeError("webhooks.endpoints.update: patch object required");
        var current = await _getEndpoint(id);
        if (!current) return null;
        var nextUrl    = current.url;
        var nextEvents = current.events;
        var nextActive = current.active;
        if (Object.prototype.hasOwnProperty.call(patch, "url")) {
          _validateUrl(patch.url);
          nextUrl = patch.url;
        }
        if (Object.prototype.hasOwnProperty.call(patch, "events")) {
          nextEvents = _validateEvents(patch.events);
        }
        if (Object.prototype.hasOwnProperty.call(patch, "active")) {
          if (patch.active !== true && patch.active !== false && patch.active !== 0 && patch.active !== 1) {
            throw new TypeError("webhooks.endpoints.update: active must be boolean / 0 / 1");
          }
          nextActive = (patch.active === true || patch.active === 1) ? 1 : 0;
        }
        var ts = _now();
        await query(
          "UPDATE webhook_endpoints SET url = ?1, events = ?2, active = ?3, updated_at = ?4 WHERE id = ?5",
          [nextUrl, nextEvents, nextActive, ts, id],
        );
        return await _getEndpoint(id);
      },

      delete: async function (id) {
        _uuid(id, "endpoint id");
        var r = await query("DELETE FROM webhook_endpoints WHERE id = ?1", [id]);
        return r.rowCount > 0;
      },
    },

    deliveries: {
      list: async function (endpointId, listOpts) {
        _uuid(endpointId, "endpoint id");
        var limit = (listOpts && Number.isInteger(listOpts.limit) && listOpts.limit > 0) ? listOpts.limit : 50;
        if (limit > 500) limit = 500;
        var r = await query(
          "SELECT * FROM webhook_deliveries WHERE endpoint_id = ?1 ORDER BY created_at DESC LIMIT ?2",
          [endpointId, limit],
        );
        return r.rows;
      },

      retry: async function (deliveryId) {
        _uuid(deliveryId, "delivery id");
        var d = await _getDelivery(deliveryId);
        if (!d) return null;
        var endpoint = await _getEndpoint(d.endpoint_id);
        if (!endpoint) return null;
        return await _attempt(deliveryId, endpoint, d.event_type, d.payload_json);
      },
    },

    send: async function (eventType, payload) {
      if (typeof eventType !== "string" || eventType.length === 0) {
        throw new TypeError("webhooks.send: eventType must be a non-empty string");
      }
      // Permit unknown event types at send time — the operator may
      // emit a custom event from a future primitive and we'd rather
      // route it through subscribed endpoints than reject it here.
      var payloadJson;
      try { payloadJson = JSON.stringify(payload == null ? {} : payload); }
      catch (e) { throw new TypeError("webhooks.send: payload must be JSON-serializable — " + (e && e.message)); }

      var r = await query("SELECT * FROM webhook_endpoints WHERE active = 1", []);
      var endpoints = r.rows;
      var matched = endpoints.filter(function (e) { return _matchEvents(e.events, eventType); });
      var deliveries = [];
      for (var i = 0; i < matched.length; i += 1) {
        // Sequential delivery — preserves ordering on the per-endpoint
        // delivery feed. Operators with high-throughput endpoints opt
        // into parallel fan-out in a follow-up primitive.
        var d = await _deliver(matched[i], eventType, payloadJson);
        deliveries.push(d);
      }
      return deliveries;
    },
  };
}

module.exports = {
  create:       create,
  KNOWN_EVENTS: KNOWN_EVENTS,
};
