"use strict";
/**
 * @module shop.webhooks
 * @title  Outbound merchant webhooks — operator-registered receivers
 *
 * @intro
 *   Operators register HTTP endpoints to receive order-state-change
 *   events. Each delivery is signed via the upstream `b.webhook`
 *   signer — the receiver verifies the framework's standard
 *   `Webhook-Signature` header (HMAC-SHA3-512 with the per-endpoint
 *   secret) using `b.webhook.verifier({...}).verify(...)`.
 *
 *   The per-endpoint secret is generated by the framework via
 *   `b.crypto.generateToken(32)` and returned ONCE on create. The
 *   operator records it for verification; the framework never reveals
 *   it again (rows stay for outbound use only).
 *
 *   `events` is either the wildcard `*` or a comma-separated allowlist
 *   of recognized event types — `order.mark_paid`,
 *   `order.start_fulfillment`, `order.mark_shipped`,
 *   `order.mark_delivered`, `order.cancel`, `order.refund`,
 *   `inventory.low_stock`. Endpoints only receive event types they
 *   subscribed to.
 *
 *   `send(eventType, payload)` is fire-and-flag-failure: every active
 *   endpoint subscribed to the event gets a delivery row before the
 *   outbound POST runs. On HTTP 1xx-3xx the row flips to
 *   `delivered_at = <ts>` + `last_status = <code>`; on 4xx/5xx (or
 *   transport error) the row holds `last_error` and a single retry
 *   runs via `b.retry.withRetry`. The framework returns the array of
 *   delivery rows so the caller (typically the order primitive) can
 *   surface failures to the operator's audit pipeline.
 *
 *   The idempotency key bound into the signed string is a fresh
 *   `b.uuid.v7()` per delivery — re-deliveries (manual retry) carry a
 *   new id so the consumer's nonce store doesn't reject the replay as
 *   a duplicate.
 *
 *   TLS posture — outbound deliveries dial through `b.httpClient`,
 *   which offers ONLY the framework's PQC-hybrid key-exchange groups
 *   (ML-KEM hybrid, `constants.TLS_GROUP_PREFERENCE`) with a TLS 1.3
 *   minimum. A receiver whose TLS stack does not yet negotiate an
 *   ML-KEM hybrid group answers the ClientHello with a
 *   handshake_failure (TLS alert 40); the framework surfaces that as a
 *   transport error, so the delivery row records `last_error`, runs the
 *   backoff retry schedule, and — if the endpoint never negotiates a
 *   supported group — lands in `webhook_dlq` after the fifth attempt.
 *   This is a deliberate posture choice, NOT a silent classical
 *   downgrade: the PSP adapters (lib/payment.js) pin a downgraded agent
 *   for their two FIXED endpoints, but a webhook receiver URL is
 *   operator-arbitrary, so the framework's PQC-first default is held.
 *   An operator whose receiver can't meet the PQC list terminates TLS
 *   for it on a fronting proxy (Cloudflare, a load balancer) that does,
 *   or upgrades the receiver's TLS stack.
 */

var b = require("./vendor/blamejs");
var textGuard = require("./text-guard");

var C = b.constants;

var KNOWN_EVENTS = Object.freeze([
  "order.mark_paid",
  "order.start_fulfillment",
  "order.mark_shipped",
  "order.mark_delivered",
  "order.cancel",
  "order.refund",
  "inventory.low_stock",
]);

var SECRET_BYTES = 32;

// Exponential backoff schedule (seconds) for failed deliveries.
//
// Budget rationale — the receiver can be down for a full day before
// we give up. The five-step ramp is deliberately conservative:
//
//   60s     → cover a transient blip (LB reload, instance restart,
//             garbage-collection pause). Quick retry catches the
//             99% of failures that resolve themselves in <1 minute.
//   300s    → after the second failure assume the outage is real;
//             back off to five minutes so we don't hammer a receiver
//             whose maintenance window is mid-deploy.
//   1800s   → thirty minutes — covers a typical incident-response
//             rollback / hotfix-deploy turnaround.
//   14400s  → four hours — covers an overnight outage where the
//             on-call hasn't been paged yet.
//   86400s  → one day — last attempt before DLQ. If a receiver is
//             still down 24h after the first failure the operator
//             needs to look at the row by hand; further retries
//             would risk DOS'ing the receiver's recovery path.
//
// After the fifth failed attempt the delivery moves to webhook_dlq
// for operator investigation — see `_moveToDlq` below.
var BACKOFF_SCHEDULE_S = Object.freeze([60, 300, 1800, 14400, 86400]); // allow:raw-time-literal — seconds values; C.TIME returns ms
var MAX_ATTEMPTS       = 5;

// processRetries claims each due delivery by pushing its next_retry_at out by
// this lease before attempting it, so a second tick that overlaps a slow pass
// skips the in-flight row instead of double-attempting it. _attempt overwrites
// next_retry_at with the real backoff (or stamps delivered_at), so the lease
// only persists if the process dies mid-attempt — in which case the row is
// retried after the lease expires. Comfortably longer than a bounded pass.
var RETRY_CLAIM_LEASE_MS = C.TIME.minutes(5);

// Window used by the per-endpoint rate-limit sliding count. One
// minute is short enough that a wedged receiver doesn't permanently
// brick its own delivery feed (the window naturally slides forward),
// long enough that bursty fan-out from a single high-volume event
// doesn't trip the throttle on a healthy endpoint.
var RATE_WINDOW_MS = C.TIME.minutes(1);

function _now() { return Date.now(); }

function _validateUrl(url) {
  if (typeof url !== "string" || url.length === 0) {
    throw new TypeError("webhooks: url must be a non-empty string");
  }
  // Refuse http:// outright for outbound — the framework's safe-url
  // parser carries the ALLOW_HTTP_TLS preset that admits only https.
  var parsed;
  try {
    parsed = b.safeUrl.parse(url, { allowedProtocols: ["https:"] });
  } catch (e) {
    throw new TypeError("webhooks: url must be https:// — " + (e && e.message || "rejected"));
  }
  // SSRF: refuse any internal / loopback / link-local / cloud-metadata
  // destination so a registered receiver can't be turned into a probe of
  // the host's own network or the instance-credential metadata service.
  // textGuard.hostLabel classifies a literal-IP host directly via the
  // framework SSRF guard (loopback / private / link-local / reserved /
  // cloud-metadata, IPv4 + IPv6 + IPv4-mapped) and matches a hostname
  // against the by-name metadata / loopback denylist plus the *.internal
  // suffix, after stripping a trailing FQDN dot + IPv6 brackets so neither
  // check is evaded. DNS-rebinding (a public name that resolves to a
  // private IP) is OUT OF SCOPE here by design — the resolving guard
  // belongs on the delivery dial.
  try {
    textGuard.hostLabel(parsed.hostname, "webhooks: url host");
  } catch (_e) {
    throw new TypeError("webhooks: url host is not allowed (internal/loopback/metadata address)");
  }
}

function _validateEvents(events) {
  if (typeof events !== "string" || events.length === 0) {
    throw new TypeError("webhooks: events must be a non-empty string ('*' or comma-separated event types)");
  }
  if (events === "*") return "*";
  var parts = events.split(",").map(function (s) { return s.trim(); }).filter(Boolean);
  if (parts.length === 0) {
    throw new TypeError("webhooks: events must list at least one event type");
  }
  for (var i = 0; i < parts.length; i += 1) {
    if (KNOWN_EVENTS.indexOf(parts[i]) === -1) {
      throw new TypeError("webhooks: unknown event type " + JSON.stringify(parts[i]) +
        " — known: " + KNOWN_EVENTS.join(", "));
    }
  }
  return parts.join(",");
}

function _matchEvents(subscribedCsv, eventType) {
  if (subscribedCsv === "*") return true;
  var parts = subscribedCsv.split(",");
  for (var i = 0; i < parts.length; i += 1) {
    if (parts[i] === eventType) return true;
  }
  return false;
}

function _uuid(s, label) {
  try { return b.guardUuid.sanitize(s, { profile: "strict" }); }
  catch (e) { throw new TypeError("webhooks: " + label + " — " + (e && e.message || "invalid UUID")); }
}

// _defaultTransport — composes b.httpClient.request for production.
// Test wiring injects a stub via deps.transport so the delivery path
// is exercised without an actual outbound POST.
function _defaultTransport(req) {
  return b.httpClient.request({
    method:  "POST",
    url:     req.url,
    headers: req.headers,
    body:    req.body,
  });
}

function create(opts) {
  opts = opts || {};
  var query = opts.query;
  if (!query) {
    query = function (sql, params) { return b.externalDb.query(sql, params); };
  }
  var transport = typeof opts.transport === "function" ? opts.transport : _defaultTransport;
  var retryOpts = opts.retry || { maxAttempts: 2, baseDelayMs: 25, maxDelayMs: 250 };
  // Operator-injectable clock — tests fast-forward through the
  // exponential backoff schedule by passing a synthetic `now()` that
  // jumps ahead by the scheduled interval. Production callers leave
  // it undefined and pick up the wall clock.
  var nowFn = (typeof opts.now === "function") ? opts.now : _now;

  async function _deliver(endpointRow, eventType, payloadJson) {
    // Rate-limit gate — count deliveries created in the last 60s for
    // this endpoint and refuse the new fan-out when the configured
    // ceiling would be exceeded. The refusal persists a delivery row
    // (last_error = "rate-limited", delivered_at = NULL, no
    // next_retry_at) so the operator sees the throttle in the admin
    // feed instead of silently dropping the event.
    var rateOk = await _checkRateLimit(endpointRow);
    if (!rateOk) {
      return await _persistRateLimited(endpointRow, eventType, payloadJson);
    }
    var deliveryId = b.uuid.v7();
    var createdAt  = nowFn();
    await query(
      "INSERT INTO webhook_deliveries (id, endpoint_id, event_type, payload_json, attempts, created_at) " +
      "VALUES (?1, ?2, ?3, ?4, 0, ?5)",
      [deliveryId, endpointRow.id, eventType, payloadJson, createdAt],
    );
    return await _attempt(deliveryId, endpointRow, eventType, payloadJson);
  }

  // The marker a refusal row carries in `last_error`. Rows bearing it are
  // EXCLUDED from the rate-limit count — a refusal is the gate's own
  // output, not a real delivery, so counting it would let the gate
  // perpetuate its own throttle: once tripped, the refusal rows alone keep
  // the window "full" and every subsequent send is refused forever even
  // after the real deliveries age out.
  var RATE_LIMITED_MARKER = "rate-limited";

  async function _checkRateLimit(endpointRow) {
    var limit = endpointRow.rate_limit_per_minute;
    if (typeof limit !== "number" || !isFinite(limit) || limit <= 0) return true;
    var windowStart = nowFn() - RATE_WINDOW_MS;
    var r = await query(
      "SELECT count(*) AS n FROM webhook_deliveries " +
      "WHERE endpoint_id = ?1 AND created_at > ?2 " +
      "AND (last_error IS NULL OR last_error != ?3)",
      [endpointRow.id, windowStart, RATE_LIMITED_MARKER],
    );
    var n = (r.rows[0] && (r.rows[0].n != null ? r.rows[0].n : r.rows[0]["count(*)"])) || 0;
    return n < limit;
  }

  // Surface a single refusal row per endpoint per window so the operator
  // sees the throttle in the admin feed — but DON'T grow the table by one
  // row per suppressed attempt. A flood of suppressed events against a
  // wedged receiver would otherwise write unbounded refusal rows. When a
  // recent refusal row already exists for this endpoint, refresh its
  // last_attempted_at (collapse) instead of inserting another.
  async function _persistRateLimited(endpointRow, eventType, payloadJson) {
    var ts = nowFn();
    var windowStart = ts - RATE_WINDOW_MS;
    var existing = await query(
      "SELECT id FROM webhook_deliveries " +
      "WHERE endpoint_id = ?1 AND last_error = ?2 AND created_at > ?3 " +
      "ORDER BY created_at DESC LIMIT 1",
      [endpointRow.id, RATE_LIMITED_MARKER, windowStart],
    );
    if (existing.rows[0]) {
      var existingId = existing.rows[0].id;
      await query(
        "UPDATE webhook_deliveries SET last_attempted_at = ?1, event_type = ?2, payload_json = ?3 " +
        "WHERE id = ?4",
        [ts, eventType, payloadJson, existingId],
      );
      return await _getDelivery(existingId);
    }
    var deliveryId = b.uuid.v7();
    await query(
      "INSERT INTO webhook_deliveries " +
      "(id, endpoint_id, event_type, payload_json, attempts, last_status, last_error, " +
      " last_attempted_at, created_at) " +
      "VALUES (?1, ?2, ?3, ?4, 0, NULL, ?5, ?6, ?7)",
      [deliveryId, endpointRow.id, eventType, payloadJson, RATE_LIMITED_MARKER, ts, ts],
    );
    return await _getDelivery(deliveryId);
  }

  async function _attempt(deliveryId, endpointRow, eventType, payloadJson) {
    var signer = b.webhook.signer({
      algo:        "hmac-sha3-512",
      keys:        { v1: Buffer.from(endpointRow.secret, "utf8") },
      defaultKid:  "v1",
      idGenerator: function () { return b.uuid.v7().replace(/-/g, ""); },
    });
    var signed = signer.sign(payloadJson);
    var headers = Object.assign({
      "Content-Type":      "application/json",
      "Webhook-Event":     eventType,
      "Webhook-Delivery":  deliveryId,
    }, signed.headers);

    var status = 0;
    var errMsg = null;
    try {
      var res = await b.retry.withRetry(function () {
        return transport({ url: endpointRow.url, headers: headers, body: payloadJson });
      }, retryOpts);
      status = (res && (res.statusCode || res.status)) || 0;
    } catch (e) {
      errMsg = (e && e.message) || String(e);
    }

    var ts = nowFn();
    var delivered = (status >= 100 && status < 400);
    if (delivered) {
      await query(
        "UPDATE webhook_deliveries SET attempts = attempts + 1, last_status = ?1, " +
        "last_error = NULL, delivered_at = ?2, last_attempted_at = ?2, next_retry_at = NULL " +
        "WHERE id = ?3",
        [status, ts, deliveryId],
      );
      return await _getDelivery(deliveryId);
    }

    // Failure path — increment attempts, record the error, then
    // either schedule the next retry (attempts < MAX_ATTEMPTS) or
    // move the delivery to webhook_dlq for operator review. The
    // backoff index uses `attempts - 1` after increment so the first
    // failure gets BACKOFF_SCHEDULE_S[0] (60s), the second gets [1]
    // (300s), etc.
    var current = await _getDelivery(deliveryId);
    var nextAttempts = ((current && current.attempts) || 0) + 1;
    var willDlq = (nextAttempts >= MAX_ATTEMPTS);
    var nextRetryAt = null;
    if (!willDlq) {
      var idx = nextAttempts - 1;
      if (idx < BACKOFF_SCHEDULE_S.length) {
        nextRetryAt = ts + (BACKOFF_SCHEDULE_S[idx] * 1000); // allow:raw-time-literal — schedule entry is a runtime seconds value; *1000 converts to ms
      }
    }
    await query(
      "UPDATE webhook_deliveries SET attempts = ?1, last_status = ?2, last_error = ?3, " +
      "last_attempted_at = ?4, next_retry_at = ?5 WHERE id = ?6",
      [nextAttempts, status || null, errMsg || ("http-" + status), ts, nextRetryAt, deliveryId],
    );
    if (willDlq) {
      await _moveToDlq(deliveryId, endpointRow, eventType, payloadJson, nextAttempts,
        status || null, errMsg || ("http-" + status), ts);
    }
    return await _getDelivery(deliveryId);
  }

  async function _moveToDlq(deliveryId, endpointRow, eventType, payloadJson, attempts,
                            lastStatus, lastError, ts) {
    // The original delivery row stays in webhook_deliveries (with
    // attempts === MAX_ATTEMPTS, delivered_at NULL) so the
    // per-endpoint feed still surfaces the failure. The DLQ row
    // carries the full payload so replayFromDlq can re-queue
    // without consulting the original delivery.
    //
    // Idempotent per delivery: the INSERT...SELECT writes only when no
    // dead-letter row already exists for this delivery_id. Without it, a
    // manual retry of an already-exhausted delivery dropped a duplicate
    // DLQ row on every click. The migration 0215 UNIQUE(delivery_id) is
    // the schema backstop; this guard avoids relying on a swallowed
    // constraint error.
    var dlqId = b.uuid.v7();
    var firstAttemptedAt;
    var r = await query(
      "SELECT created_at FROM webhook_deliveries WHERE id = ?1",
      [deliveryId],
    );
    firstAttemptedAt = (r.rows[0] && r.rows[0].created_at) || ts;
    await query(
      "INSERT INTO webhook_dlq " +
      "(id, endpoint_id, delivery_id, event_type, payload_json, attempts, " +
      " last_status, last_error, first_attempted_at, last_attempted_at, dropped_at) " +
      "SELECT ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11 " +
      "WHERE NOT EXISTS (SELECT 1 FROM webhook_dlq WHERE delivery_id = ?3)",
      [dlqId, endpointRow.id, deliveryId, eventType, payloadJson, attempts,
       lastStatus, lastError, firstAttemptedAt, ts, ts],
    );
  }

  async function _getDelivery(id) {
    var r = await query("SELECT * FROM webhook_deliveries WHERE id = ?1", [id]);
    return r.rows[0] || null;
  }

  async function _getEndpoint(id) {
    var r = await query("SELECT * FROM webhook_endpoints WHERE id = ?1", [id]);
    return r.rows[0] || null;
  }

  return {
    KNOWN_EVENTS: KNOWN_EVENTS,

    endpoints: {
      create: async function (input) {
        if (!input || typeof input !== "object") throw new TypeError("webhooks.endpoints.create: input object required");
        _validateUrl(input.url);
        var events = _validateEvents(input.events);
        var id     = b.uuid.v7();
        var secret = b.crypto.generateToken(SECRET_BYTES);
        var ts     = _now();
        // rate_limit_per_minute defaults to 60 at the schema level
        // (see migration 0017). Operators wiring a slow receiver opt
        // into a lower ceiling on create; raising it past the default
        // is supported but undocumented — most receivers handle 60
        // req/min comfortably.
        var rate = 60;
        if (Object.prototype.hasOwnProperty.call(input, "rate_limit_per_minute")) {
          if (typeof input.rate_limit_per_minute !== "number" ||
              !Number.isInteger(input.rate_limit_per_minute) ||
              input.rate_limit_per_minute <= 0) {
            throw new TypeError("webhooks.endpoints.create: rate_limit_per_minute must be a positive integer");
          }
          rate = input.rate_limit_per_minute;
        }
        await query(
          "INSERT INTO webhook_endpoints " +
          "(id, url, secret, events, active, rate_limit_per_minute, created_at, updated_at) " +
          "VALUES (?1, ?2, ?3, ?4, 1, ?5, ?6, ?6)",
          [id, input.url, secret, events, rate, ts],
        );
        return await _getEndpoint(id);
      },

      get: async function (id) {
        _uuid(id, "endpoint id");
        return await _getEndpoint(id);
      },

      list: async function () {
        var r = await query("SELECT * FROM webhook_endpoints ORDER BY created_at DESC", []);
        return r.rows;
      },

      update: async function (id, patch) {
        _uuid(id, "endpoint id");
        if (!patch || typeof patch !== "object") throw new TypeError("webhooks.endpoints.update: patch object required");
        var current = await _getEndpoint(id);
        if (!current) return null;
        var nextUrl    = current.url;
        var nextEvents = current.events;
        var nextActive = current.active;
        var nextRate   = current.rate_limit_per_minute;
        if (Object.prototype.hasOwnProperty.call(patch, "url")) {
          _validateUrl(patch.url);
          nextUrl = patch.url;
        }
        if (Object.prototype.hasOwnProperty.call(patch, "events")) {
          nextEvents = _validateEvents(patch.events);
        }
        if (Object.prototype.hasOwnProperty.call(patch, "active")) {
          if (patch.active !== true && patch.active !== false && patch.active !== 0 && patch.active !== 1) {
            throw new TypeError("webhooks.endpoints.update: active must be boolean / 0 / 1");
          }
          nextActive = (patch.active === true || patch.active === 1) ? 1 : 0;
        }
        if (Object.prototype.hasOwnProperty.call(patch, "rate_limit_per_minute")) {
          var rate = patch.rate_limit_per_minute;
          if (typeof rate !== "number" || !Number.isInteger(rate) || rate <= 0) {
            throw new TypeError("webhooks.endpoints.update: rate_limit_per_minute must be a positive integer");
          }
          nextRate = rate;
        }
        var ts = _now();
        await query(
          "UPDATE webhook_endpoints SET url = ?1, events = ?2, active = ?3, " +
          "rate_limit_per_minute = ?4, updated_at = ?5 WHERE id = ?6",
          [nextUrl, nextEvents, nextActive, nextRate, ts, id],
        );
        return await _getEndpoint(id);
      },

      delete: async function (id) {
        _uuid(id, "endpoint id");
        var r = await query("DELETE FROM webhook_endpoints WHERE id = ?1", [id]);
        return r.rowCount > 0;
      },
    },

    deliveries: {
      list: async function (endpointId, listOpts) {
        _uuid(endpointId, "endpoint id");
        var limit = (listOpts && Number.isInteger(listOpts.limit) && listOpts.limit > 0) ? listOpts.limit : 50;
        if (limit > 500) limit = 500;
        var r = await query(
          "SELECT * FROM webhook_deliveries WHERE endpoint_id = ?1 ORDER BY created_at DESC LIMIT ?2",
          [endpointId, limit],
        );
        return r.rows;
      },

      retry: async function (deliveryId) {
        _uuid(deliveryId, "delivery id");
        var d = await _getDelivery(deliveryId);
        if (!d) return null;
        // An exhausted delivery (attempts at/over the max) has already
        // moved to the DLQ — re-attempting it would push attempts past the
        // max and drop a DUPLICATE DLQ row on every click. Answer a no-op
        // (return the row unchanged) so the operator UI shows the existing
        // state; re-queuing an exhausted delivery is `replayFromDlq`, not
        // `retry`. A successfully-delivered row is likewise a no-op.
        var attempts = Number(d.attempts || 0);
        if (attempts >= MAX_ATTEMPTS || d.delivered_at != null) {
          return d;
        }
        var endpoint = await _getEndpoint(d.endpoint_id);
        if (!endpoint) return null;
        return await _attempt(deliveryId, endpoint, d.event_type, d.payload_json);
      },
    },

    dlq: {
      list: async function (endpointId, listOpts) {
        _uuid(endpointId, "endpoint id");
        var limit = (listOpts && Number.isInteger(listOpts.limit) && listOpts.limit > 0) ? listOpts.limit : 50;
        if (limit > 500) limit = 500;
        var r = await query(
          "SELECT * FROM webhook_dlq WHERE endpoint_id = ?1 ORDER BY dropped_at DESC LIMIT ?2",
          [endpointId, limit],
        );
        return r.rows;
      },

      get: async function (id) {
        _uuid(id, "dlq id");
        var r = await query("SELECT * FROM webhook_dlq WHERE id = ?1", [id]);
        return r.rows[0] || null;
      },
    },

    // Re-queue a DLQ row as a fresh delivery on its original
    // endpoint. The DLQ row is removed once the new delivery row is
    // persisted — keeping both would leave duplicate state for the
    // admin feed to reconcile. The new delivery starts at attempts=0
    // so the full backoff schedule applies if the receiver is still
    // unhappy.
    replayFromDlq: async function (dlqId) {
      _uuid(dlqId, "dlq id");
      var r = await query("SELECT * FROM webhook_dlq WHERE id = ?1", [dlqId]);
      var row = r.rows[0];
      if (!row) return null;
      var endpoint = await _getEndpoint(row.endpoint_id);
      if (!endpoint) return null;
      // Delete first — if the subsequent _deliver fails we don't
      // want a permanent ghost; the new delivery row carries the
      // failure state forward and (on five failures) lands back in
      // the DLQ as a fresh row.
      await query("DELETE FROM webhook_dlq WHERE id = ?1", [dlqId]);
      return await _deliver(endpoint, row.event_type, row.payload_json);
    },

    // Polled scheduler entry point — picks deliveries whose next_retry_at has
    // come due and re-attempts each. The worker's scheduled() handler drives
    // this once a minute via the container's /_/webhook-retry-tick route.
    // Returns the list of deliveries the call actually attempted (the ones it
    // won the claim on).
    //
    // Each row is claimed with an atomic conditional UPDATE before it is
    // attempted, so two overlapping ticks (a slow pass still running when the
    // next minute fires) can never double-attempt the same delivery — the
    // claim moves next_retry_at out of the due window, and only the tick whose
    // UPDATE matched (rowCount === 1) calls _attempt.
    processRetries: async function (procOpts) {
      var now = (procOpts && typeof procOpts.now === "number") ? procOpts.now : nowFn();
      var max = (procOpts && Number.isInteger(procOpts.max) && procOpts.max > 0) ? procOpts.max : 100;
      if (max > 1000) max = 1000;
      var r = await query(
        "SELECT * FROM webhook_deliveries " +
        "WHERE next_retry_at IS NOT NULL AND next_retry_at <= ?1 AND delivered_at IS NULL " +
        "ORDER BY next_retry_at ASC LIMIT ?2",
        [now, max],
      );
      var attempted = [];
      for (var i = 0; i < r.rows.length; i += 1) {
        var row = r.rows[i];
        // Skip a delivery whose endpoint has been deleted or PAUSED. Normal
        // fan-out only sends to active endpoints, so the automatic cron must
        // not keep POSTing to one an operator explicitly disabled. Checked
        // BEFORE the claim, so a paused endpoint's pending retries keep their
        // schedule position (next_retry_at untouched) and resume when it is
        // re-enabled, rather than the lease churning forward every tick. A
        // manual admin retry remains an explicit operator override.
        var endpoint = await _getEndpoint(row.endpoint_id);
        if (!endpoint || !(endpoint.active === 1 || endpoint.active === true)) continue;
        // Atomic claim: push next_retry_at out by the lease so a concurrent
        // tick's identical WHERE no longer matches this row. Only the winner
        // (rowCount === 1) attempts; _attempt then overwrites next_retry_at
        // with the real backoff or stamps delivered_at.
        var claim = await query(
          "UPDATE webhook_deliveries SET next_retry_at = ?1 " +
          "WHERE id = ?2 AND next_retry_at IS NOT NULL AND next_retry_at <= ?3 AND delivered_at IS NULL",
          [now + RETRY_CLAIM_LEASE_MS, row.id, now],
        );
        var claimed = claim && (claim.rowCount != null ? claim.rowCount
          : (claim.meta && claim.meta.changes != null ? claim.meta.changes : claim.changes));
        if (Number(claimed || 0) !== 1) continue;   // lost the claim to a concurrent tick
        var d = await _attempt(row.id, endpoint, row.event_type, row.payload_json);
        attempted.push(d);
      }
      return attempted;
    },

    // Inbound signature verification — operators receiving webhooks
    // from peers (or replaying their own outbound for end-to-end
    // testing) call this to validate the Stripe-shaped header
    // `t=<unix>,v1=<hmac-sha256(secret, ts + "." + body)>` before
    // trusting the payload. Delegates to b.webhook.verify — the
    // framework's Stripe-compatible verifier handles tolerance,
    // constant-time compare, and HMAC-SHA-256 computation.
    //
    // `toleranceSeconds` defaults to 300 (5 min) to match the
    // framework default; the floor is 30 s — anything shorter risks
    // false rejects from clock skew.
    verifyIncoming: async function (payload, signatureHeader, secret, toleranceSeconds) {
      if (payload == null) {
        throw new TypeError("webhooks.verifyIncoming: payload required");
      }
      if (typeof signatureHeader !== "string" || signatureHeader.length === 0) {
        throw new TypeError("webhooks.verifyIncoming: signatureHeader must be a non-empty string");
      }
      if ((typeof secret !== "string" || secret.length === 0) && !Buffer.isBuffer(secret)) {
        throw new TypeError("webhooks.verifyIncoming: secret must be a non-empty string or Buffer");
      }
      var tolMs;
      if (toleranceSeconds === undefined) {
        tolMs = C.TIME.minutes(5);
      } else {
        if (typeof toleranceSeconds !== "number" || !isFinite(toleranceSeconds) || toleranceSeconds < 30) {
          throw new TypeError("webhooks.verifyIncoming: toleranceSeconds must be >= 30");
        }
        tolMs = Math.floor(toleranceSeconds * 1000); // allow:raw-time-literal — toleranceSeconds is a runtime seconds value; *1000 converts to ms
      }
      return await b.webhook.verify({
        alg:         "hmac-sha256-stripe",
        secret:      secret,
        header:      signatureHeader,
        body:        payload,
        toleranceMs: tolMs,
      });
    },

    // Companion to verifyIncoming — produce the Stripe-shaped
    // `t=<unix>,v1=<hex>` header for a given payload + secret. The
    // round-trip is what end-to-end tests + downstream emitters
    // need; operators forwarding events to peer systems use this to
    // sign the relay body.
    signOutgoing: function (payload, secret, timestampSeconds) {
      if (payload == null) {
        throw new TypeError("webhooks.signOutgoing: payload required");
      }
      if ((typeof secret !== "string" || secret.length === 0) && !Buffer.isBuffer(secret)) {
        throw new TypeError("webhooks.signOutgoing: secret must be a non-empty string or Buffer");
      }
      var input = {
        alg:    "hmac-sha256-stripe",
        secret: secret,
        body:   payload,
      };
      if (timestampSeconds !== undefined) input.timestamp = timestampSeconds;
      return b.webhook.sign(input);
    },

    BACKOFF_SCHEDULE_S: BACKOFF_SCHEDULE_S,
    MAX_ATTEMPTS:       MAX_ATTEMPTS,

    send: async function (eventType, payload) {
      if (typeof eventType !== "string" || eventType.length === 0) {
        throw new TypeError("webhooks.send: eventType must be a non-empty string");
      }
      // Permit unknown event types at send time — the operator may
      // emit a custom event from a future primitive and we'd rather
      // route it through subscribed endpoints than reject it here.
      var payloadJson;
      try { payloadJson = JSON.stringify(payload == null ? {} : payload); }
      catch (e) { throw new TypeError("webhooks.send: payload must be JSON-serializable — " + (e && e.message)); }

      var r = await query("SELECT * FROM webhook_endpoints WHERE active = 1", []);
      var endpoints = r.rows;
      var matched = endpoints.filter(function (e) { return _matchEvents(e.events, eventType); });
      var deliveries = [];
      for (var i = 0; i < matched.length; i += 1) {
        // Sequential delivery — preserves ordering on the per-endpoint
        // delivery feed. Operators with high-throughput endpoints opt
        // into parallel fan-out in a follow-up primitive.
        var d = await _deliver(matched[i], eventType, payloadJson);
        deliveries.push(d);
      }
      return deliveries;
    },
  };
}

module.exports = {
  create:             create,
  KNOWN_EVENTS:       KNOWN_EVENTS,
  BACKOFF_SCHEDULE_S: BACKOFF_SCHEDULE_S,
  MAX_ATTEMPTS:       MAX_ATTEMPTS,
};
